#!/bin/bash

set -x

sudo apt-get update -qq
sudo apt-get install -y cpio realpath squashfs-tools
sudo apt-get install -y strace gdb libcap-ng-utils

sudo apt-get install -y coreutils # systemd needs a recent /bin/ln
sudo apt-get install -y gperf libcap-dev linux-headers-amd64 # systemd deps

sudo apt-get install -y git # cloning a tag of systemd

export RKT_STAGE1_USR_FROM=src ; ./test
./test-functional


